"""empty message

Revision ID: 4e44d8ddd7ef
Revises: 
Create Date: 2021-03-02 06:12:43.901364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e44d8ddd7ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=False)
    op.create_index(op.f('ix_group_time'), 'group', ['time'], unique=False)
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('Question', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Question'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_name'), 'module', ['name'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('anwser', sa.String(length=100), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_anwser'), 'question', ['anwser'], unique=False)
    op.create_index(op.f('ix_question_text'), 'question', ['text'], unique=False)
    op.create_table('solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homework_solution', sa.String(length=120), nullable=True),
    sa.Column('ticket', sa.Integer(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_comment'), 'solution', ['comment'], unique=False)
    op.create_index(op.f('ix_solution_homework_solution'), 'solution', ['homework_solution'], unique=False)
    op.create_index(op.f('ix_solution_mark'), 'solution', ['mark'], unique=False)
    op.create_table('sys_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=True),
    sa.Column('patronim', sa.String(length=120), nullable=True),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_admin_login'), 'sys_admin', ['login'], unique=False)
    op.create_index(op.f('ix_sys_admin_name'), 'sys_admin', ['name'], unique=False)
    op.create_index(op.f('ix_sys_admin_password'), 'sys_admin', ['password'], unique=False)
    op.create_index(op.f('ix_sys_admin_patronim'), 'sys_admin', ['patronim'], unique=False)
    op.create_index(op.f('ix_sys_admin_surname'), 'sys_admin', ['surname'], unique=False)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=True),
    sa.Column('patronim', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_email'), 'teacher', ['email'], unique=False)
    op.create_index(op.f('ix_teacher_login'), 'teacher', ['login'], unique=False)
    op.create_index(op.f('ix_teacher_name'), 'teacher', ['name'], unique=False)
    op.create_index(op.f('ix_teacher_password'), 'teacher', ['password'], unique=False)
    op.create_index(op.f('ix_teacher_patronim'), 'teacher', ['patronim'], unique=False)
    op.create_index(op.f('ix_teacher_phone'), 'teacher', ['phone'], unique=False)
    op.create_index(op.f('ix_teacher_surname'), 'teacher', ['surname'], unique=False)
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ids', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_ids'), 'ticket', ['ids'], unique=False)
    op.create_table('group_teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], )
    )
    op.create_table('pupil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=True),
    sa.Column('patronim', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('pupil_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['pupil_id'], ['solution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pupil_email'), 'pupil', ['email'], unique=False)
    op.create_index(op.f('ix_pupil_login'), 'pupil', ['login'], unique=False)
    op.create_index(op.f('ix_pupil_name'), 'pupil', ['name'], unique=False)
    op.create_index(op.f('ix_pupil_password'), 'pupil', ['password'], unique=False)
    op.create_index(op.f('ix_pupil_patronim'), 'pupil', ['patronim'], unique=False)
    op.create_index(op.f('ix_pupil_phone'), 'pupil', ['phone'], unique=False)
    op.create_index(op.f('ix_pupil_surname'), 'pupil', ['surname'], unique=False)
    op.create_table('group_pupils',
    sa.Column('pupil_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupil.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_pupils')
    op.drop_index(op.f('ix_pupil_surname'), table_name='pupil')
    op.drop_index(op.f('ix_pupil_phone'), table_name='pupil')
    op.drop_index(op.f('ix_pupil_patronim'), table_name='pupil')
    op.drop_index(op.f('ix_pupil_password'), table_name='pupil')
    op.drop_index(op.f('ix_pupil_name'), table_name='pupil')
    op.drop_index(op.f('ix_pupil_login'), table_name='pupil')
    op.drop_index(op.f('ix_pupil_email'), table_name='pupil')
    op.drop_table('pupil')
    op.drop_table('group_teachers')
    op.drop_index(op.f('ix_ticket_ids'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_teacher_surname'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_phone'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_patronim'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_password'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_name'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_login'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_email'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_sys_admin_surname'), table_name='sys_admin')
    op.drop_index(op.f('ix_sys_admin_patronim'), table_name='sys_admin')
    op.drop_index(op.f('ix_sys_admin_password'), table_name='sys_admin')
    op.drop_index(op.f('ix_sys_admin_name'), table_name='sys_admin')
    op.drop_index(op.f('ix_sys_admin_login'), table_name='sys_admin')
    op.drop_table('sys_admin')
    op.drop_index(op.f('ix_solution_mark'), table_name='solution')
    op.drop_index(op.f('ix_solution_homework_solution'), table_name='solution')
    op.drop_index(op.f('ix_solution_comment'), table_name='solution')
    op.drop_table('solution')
    op.drop_index(op.f('ix_question_text'), table_name='question')
    op.drop_index(op.f('ix_question_anwser'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_module_name'), table_name='module')
    op.drop_table('module')
    op.drop_index(op.f('ix_group_time'), table_name='group')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
