"""empty message

Revision ID: 5376dfc2f090
Revises: 19792c1e75db
Create Date: 2021-03-01 18:59:20.712539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5376dfc2f090'
down_revision = '19792c1e75db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pupil', sa.Column('role1', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pupil', 'role1')
    # ### end Alembic commands ###
