"""empty message

Revision ID: 5a55f86b55bc
Revises: 97f32fae4af0
Create Date: 2021-03-04 00:28:19.272532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a55f86b55bc'
down_revision = '97f32fae4af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'group_id')
    # ### end Alembic commands ###
