"""empty message

Revision ID: 68461f9f9e19
Revises: 5376dfc2f090
Create Date: 2021-03-01 18:59:49.283853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68461f9f9e19'
down_revision = '5376dfc2f090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pupil', 'role1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pupil', sa.Column('role1', sa.SMALLINT(), nullable=True))
    # ### end Alembic commands ###
