"""empty message

Revision ID: 97f32fae4af0
Revises: 26d125c11f8a
Create Date: 2021-03-03 23:06:24.844697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f32fae4af0'
down_revision = '26d125c11f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'date')
    # ### end Alembic commands ###
