"""empty message

Revision ID: cab55d22a896
Revises: 94483053d02d
Create Date: 2021-03-01 23:42:39.102131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab55d22a896'
down_revision = '94483053d02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_admin', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('sys_admin', sa.Column('patronim', sa.String(length=120), nullable=True))
    op.add_column('sys_admin', sa.Column('surname', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_sys_admin_name'), 'sys_admin', ['name'], unique=False)
    op.create_index(op.f('ix_sys_admin_patronim'), 'sys_admin', ['patronim'], unique=False)
    op.create_index(op.f('ix_sys_admin_surname'), 'sys_admin', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_admin_surname'), table_name='sys_admin')
    op.drop_index(op.f('ix_sys_admin_patronim'), table_name='sys_admin')
    op.drop_index(op.f('ix_sys_admin_name'), table_name='sys_admin')
    op.drop_column('sys_admin', 'surname')
    op.drop_column('sys_admin', 'patronim')
    op.drop_column('sys_admin', 'name')
    # ### end Alembic commands ###
