"""empty message

Revision ID: f97771ad2357
Revises: 1124c5cb5239
Create Date: 2021-03-04 12:09:12.553099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97771ad2357'
down_revision = '1124c5cb5239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=True),
    sa.Column('patronim', sa.String(length=120), nullable=True),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_admin_login'), 'teacher_admin', ['login'], unique=False)
    op.create_index(op.f('ix_teacher_admin_name'), 'teacher_admin', ['name'], unique=False)
    op.create_index(op.f('ix_teacher_admin_password'), 'teacher_admin', ['password'], unique=False)
    op.create_index(op.f('ix_teacher_admin_patronim'), 'teacher_admin', ['patronim'], unique=False)
    op.create_index(op.f('ix_teacher_admin_surname'), 'teacher_admin', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_admin_surname'), table_name='teacher_admin')
    op.drop_index(op.f('ix_teacher_admin_patronim'), table_name='teacher_admin')
    op.drop_index(op.f('ix_teacher_admin_password'), table_name='teacher_admin')
    op.drop_index(op.f('ix_teacher_admin_name'), table_name='teacher_admin')
    op.drop_index(op.f('ix_teacher_admin_login'), table_name='teacher_admin')
    op.drop_table('teacher_admin')
    # ### end Alembic commands ###
